import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { ArrowRight } from "lucide-react"

// Sub-unit data
const subUnits = [
  {
    id: 1,
    name: "Acid Angel from Asia",
    members: ["HyeRin", "YooYeon", "NaKyoung", "YuBin"],
    concept: "Dance, Electro, Cyberpunk",
    description:
      "Acid Angel from Asia's concept seems to be based on and representing the current youth of Asia, with a particular focus on South Korean youth culture and Generation Z.",
    image: "/sub-units/sub_unit_AAA.jpg",
  },
  {
    id: 2,
    name: "+(KR)ystal Eyes",
    members: ["SeoYeon", "JiWoo", "ChaeYeon", "SooMin"],
    concept: "Pop, Glam, Elegant",
    description:
      "+(KR)ystal Eyes seems to represent the High-teen, Gen Z youth of today and whilst not completely paralleling Acid Angel from Asia, the unit has a much more refreshing, white angel/fairy image that juxtaposes AAA's dark angel and rebellious portrayal.",
    image: "/sub-units/sub_unit_KRE.jpg",
  },
  {
    id: 3,
    name: "ACID EYES",
    members: ["SeoYeon", "HyeRin", "JiWoo", "ChaeYeon", "YooYeon", "SooMin", "NaKyoung", "YuBin"],
    concept: "Collaboration Sub-unit",
    description:
      "ACID EYES (Hangul: 애시드아이즈) is the first collaboration sub-unit of tripleS, consisting of all members from the units, Acid Angel from Asia and +(KR)ystal Eyes.",
    image: "/sub-units/sub_unit_ACID_EYES.jpg",
  },
  {
    id: 4,
    name: "LOVElution",
    members: ["SeoYeon", "HyeRin", "YuBin", "Kaede", "DaHyun", "Nien", "SoHyun", "Xinyu"],
    concept: "Lovely Pop",
    description:
      "LOVElution concept is about self-confidence within our Generation and youth. The Girls Capitalism music video is all about loving yourself, as shown in the “10 Rules of the Mad Money Club“.",
    image: "/sub-units/sub_unit_Lovelution.jpg",
  },
  {
    id: 5,
    name: "EVOLution",
    members: ["JiWoo", "ChaeYeon", "YooYeon", "SooMin", "NaKyoung", "Kotone", "YeonJi", "Mayu"],
    concept: "Fresh & Youthful",
    description:
      "EVOLution's concept involves tripleS' main storyline of “Among the girls inhabiting Earth, there are some who hold special abilities. We decided to call these girls with special abilities, s, through Dimension, the girls of tripleS join forces and demonstrate each of their abilities“.",
    image: "/sub-units/sub_unit_EVOLution.jpg",
  },
  {
    id: 6,
    name: "NXT",
    members: ["Lynn", "JooBin", "HaYeon", "ShiOn"],
    concept: "Dance & Youthful",
    description:
      "NXT (Hangul: 넥스트) is tripleS' fifth sub-unit. The unit was created with the purpose of revealing members Lynn, JooBin, Jeong HaYeon and Park ShiOn. They debuted with the digital single, “Just Do It”, on December 23, 2023.",
    image: "/sub-units/sub_unit_TripleS_NXT.jpg",
  },
  {
    id: 7,
    name: "Aria",
    members: ["JiWoo", "ChaeYeon", "Kaede", "DaHyun", "Nien"],
    concept: "Ballad",
    description:
      "Aria (아리아) is the seventh sub-unit and first ballad sub-unit of tripleS. They made their debut on January 15, 2024 with their single album, Structure of Sadness, and the title track, “Door”. ",
    image: "/sub-units/sub_unit_Aria_Door.jpg",
  },
  {
    id: 8,
    name: "Glow",
    members: ["ChaeWon", "Sullin", "SeoAh", "JiYeon"],
    concept: "Fresh & Youthful",
    description:
      "Glow (Hangul: 글로우) is a non-voted for tripleS sub-unit consisting of the last four revealed members of tripleS. They made their debut with their digital single, “Inner Dance”, on June 21, 2024.",
    image: "/sub-units/sub_unit_Glow.jpg",
  },
  {
    id: 9,
    name: "Vision@ry Vision",
    members: ["HyeRin", "YooYeon", "NaKyoung", "YuBin", "Kaede", "Kotone", "YeonJi", "Nien", "SoHyun", "Xinyu", "Lynn", "JiYeon"],
    concept: "Dance Unit",
    description:
      "Visionary Vision (Stylized as Vision@ry Vision or tripleS VV) is tripleS' eighth sub-unit, and the first dance-orientated unit.",
    image: "/sub-units/sub_unit_Visionary_Vision.jpg",
  },
  {
    id: 10,
    name: "∞! (Hatch!)",
    members: ["JiWoo", "ChaeYeon", "SooMin", "YooYeon", "Kotone", "Mayu", "ShiOn", "ChaeWon"],
    concept: "J-Pop",
    description:
      "∞! (Japanese: ハッチ, Hangul: 핫찌; pronounced: Hatchi, also stylised as Hatch!) is tripleS' Japanese sub-unit. They will make their debut on November 20, 2024 with their single album, “Untitled”. ",
    image: "/sub-units/sub_unit_hatchi.jpg",
  },
]

export const metadata: Metadata = {
  title: "tripleS Sub-Units | AAA, +(KR)ystal Eyes, Aria, VV & more",
  description: "Discover all tripleS (트리플에스) sub-units generated by Gravity. Check out Acid Angel from Asia, +(KR)ystal Eyes, LOVElution, EVOLution, Aria, Vision@ry Vision, Glow, and Hatch!.",
  openGraph: {
    title: "tripleS Sub-Units | AAA, +(KR)ystal Eyes, Aria, VV & more",
    description: "Discover all tripleS (트리플에스) sub-units generated by Gravity.",
    url: "https://profile-triples.vercel.app/sub-units",
    siteName: "tripleS Profile DB",
    images: [
      {
        url: "https://i.imgur.com/vHqYhWc.jpeg",
        width: 1200,
        height: 630,
        alt: "tripleS Group Photo",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "tripleS Sub-Units | AAA, +(KR)ystal Eyes, Aria, VV & more",
    description: "Discover all tripleS (트리플에스) sub-units generated by Gravity.",
    images: ["https://i.imgur.com/vHqYhWc.jpeg"],
  },
}

export default function SubUnitsPage() {
  return (
    <div className="bg-[#050505] text-white pt-24 pb-28 selection:bg-white selection:text-black">
      <div className="max-w-7xl mx-auto px-4">
        {/* Header */}
        <div className="mb-16">
          <p className="text-xs uppercase tracking-widest text-zinc-400 mb-2 font-mono">[ GRAVITY & COMBINATIONS ]</p>
          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight">
            Sub-Units & Dimensions
          </h1>
          <p className="text-base md:text-lg text-zinc-400 mt-4 max-w-3xl leading-relaxed">
            tripleS operates through dynamic subunit formations (Dimensions) created through fan-participatory Grand Gravity events. Each Dimension debuts with unique concepts, music styles, and member configurations.
          </p>
        </div>

        {/* Sub-Units List */}
        <div className="space-y-24">
          {subUnits.map((unit, index) => (
            <div
              key={unit.id}
              className={`grid grid-cols-1 ${index % 2 === 0 ? "lg:grid-cols-[1fr_1.2fr]" : "lg:grid-cols-[1.2fr_1fr]"} gap-8 lg:gap-14 items-center p-8 rounded-3xl border border-zinc-800/80 bg-zinc-900/30`}
            >
              <div className={`${index % 2 !== 0 && "lg:order-2"}`}>
                <div className="relative group overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-950">
                  <Image
                    src={unit.image || "/placeholder.svg"}
                    alt={unit.name}
                    width={600}
                    height={400}
                    className="rounded-2xl object-cover w-full aspect-video transition-transform duration-700 group-hover:scale-105"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"></div>
                  <div className="absolute top-4 left-4">
                    <span className="text-xs font-mono px-3 py-1 rounded-full bg-black/70 backdrop-blur-md border border-white/10 text-zinc-300">
                      DIMENSION #{String(unit.id).padStart(2, "0")}
                    </span>
                  </div>
                </div>
              </div>

              <div className={`${index % 2 !== 0 && "lg:order-1"} space-y-5`}>
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-zinc-800/80 border border-zinc-700 text-xs font-mono uppercase tracking-wider text-zinc-300">
                  {unit.concept}
                </div>

                <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight text-white">{unit.name}</h2>
                <p className="text-zinc-400 text-sm md:text-base leading-relaxed">{unit.description}</p>

                <div className="pt-2">
                  <span className="text-xs font-mono uppercase tracking-widest text-zinc-500 block mb-3">Unit Members</span>
                  <div className="flex flex-wrap gap-2">
                    {unit.members.map((member, i) => (
                      <span
                        key={i}
                        className="px-3 py-1 bg-zinc-800/60 border border-zinc-700/80 rounded-full text-xs font-medium text-zinc-300 hover:bg-white hover:text-black transition-colors"
                      >
                        {member}
                      </span>
                    ))}
                  </div>
                </div>

                <div className="pt-2">
                  <Link
                    href={`/members`}
                    className="inline-flex items-center gap-2 text-xs uppercase tracking-wider font-semibold text-white hover:text-zinc-300 transition-colors"
                  >
                    View member profiles <ArrowRight className="h-3.5 w-3.5" />
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer Callout */}
        <div className="mt-24 p-10 rounded-3xl border border-zinc-800 bg-zinc-900/40 text-center max-w-4xl mx-auto">
          <p className="text-xs uppercase tracking-widest text-zinc-400 mb-2 font-mono">[ PARTICIPATION ]</p>
          <h2 className="text-2xl md:text-3xl font-bold mb-4 text-white">Join Next Grand Gravity</h2>
          <p className="text-zinc-400 text-sm md:text-base mb-8 max-w-2xl mx-auto leading-relaxed">
            New Dimensions are continually voted on by WAVs across the world via COMO voting on Cosmo. Stay connected to cast your vote for upcoming unit line-ups.
          </p>
          <Link
            href="/about"
            className="inline-flex items-center justify-center gap-2 bg-white text-black px-7 py-3.5 rounded-full text-sm font-semibold hover:bg-zinc-200 transition-all tracking-wide"
          >
            Learn How Gravity Works <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    </div>
  )
}